language: ruby
rvm:
- 2.3.1
script:
- bin/rails db:migrate RAILS_ENV=test --trace
branches:
  only:
  - master
deploy:
  provider: script
  script: bash ./deploy.sh
  on: master
before_install:
  - openssl aes-256-cbc -K $encrypted_6a9b6433a992_key -iv $encrypted_6a9b6433a992_iv
    -in deploy.key.enc -out deploy.key -d
  - chmod +x ./deploy.sh
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy.key
  - ssh-add .travis/deploy.key
  - ssh-keyscan daleslab.com >> ~/.ssh/known_hosts
  - git remote add deploy dokku@daleslab.com:bendrocorp-api
  - git config --global push.default simple
