development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: bendrocorp-api_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: bendrocorp-api_production
