:schedule:
  offender_worker:
    every: 5m   # Runs once per minute
    class: OffenderScraperWorker
  kaiden_worker:
    every: 5m   # Runs once per minute
    class: KaidenEventAnnouncerWorker
  dormant_approval_worker:
    cron: '0 20 * * *'   # Run at 10pm UTC every day
    class: DormantApprovalWorker
