
apiVersion: v1
kind: Service
metadata:
  name: krakend-bendro-service
  labels:
    app: krakend-bendro-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: bendro-krakend-deployment