apiVersion: apps/v1
kind: Deployment
metadata:
  name: bendro-api-v1-deployment
spec:
  selector:
    matchLabels:
      app: bendro-api-v1-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: bendro-api-v1-deployment
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: bendro-api-v1-deployment
        image: ghcr.io/bendrocorp/bendrocorp-api-v1 # docker.pkg.github.com/bendrocorp/bendrocorp-api/bendrocorp-api-v1:latest # 
        env:
        - name: RACK_ENV
          valueFrom:
            secretKeyRef:
              name: bendro-v1-api-secrets
              key: RACK_ENV
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              name: bendro-v1-api-secrets
              key: RAILS_ENV
        - name: RAILS_LOG_TO_STDOUT
          valueFrom:
            secretKeyRef:
              name: bendro-v1-api-secrets
              key: RAILS_LOG_TO_STDOUT
        - name: RAILS_SERVE_STATIC_FILES
          valueFrom:
            secretKeyRef:
              name: bendro-v1-api-secrets
              key: RAILS_SERVE_STATIC_FILES
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: bendro-v1-api-secrets
              key: RAILS_MASTER_KEY
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        command: [ "rails" ]
        args: [ "s", "-p", "3000", "-e", "production" ]
      imagePullSecrets:
        - name: github-docker-secret