name: Ruby

on:
  push:
    branches: [ master ]

jobs:
  master-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # required for dokku
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.5
    - name: Install dependencies
      run: bundle install
    #- name: Run tests
    #  run: bundle exec rake
    - name: Push to Dokku
      uses: obrassard/action-dokku-push@v1.0.2
      with:
        # The dokku app's git repository url (in SSH format)
        dokku_repo: ${{ secrets.dokkuRepo }}
        # A private SSH key that has push acces to your Dokku instance
        ssh_key: ${{ secrets.dokkuPrivateKey }}
        # The branch to be deployed when pushing to Dokku (default: master)
        deploy_branch: master # optional, default is master
